### ISSUE TITLE
Models you train 'index.bin', 'labels.pkl', 'Backbone.pth' files?

### ISSUE THREAD

**Issue by hoangtdTcom** [sankovalev/Look4Face#5]
can you tell me which models you train 'index.bin', 'labels.pkl', 'Backbone.pth' files? 

Thank you for reading

**Comment by sankovalev** [comment]
I trained ResNet50 on MS1M-Arcface (see the section 'briefly' in the README).
Face search is performed using the LFW dataset (see 'briefly' again), 'labels.pkl' is just a dictionary like id:person_name for LFW.
'index.bin' is a faiss index for LFW dataset, so if you take a model, extract features from all photos from the LFW dataset, and add them to the index, you will get exactly this.

**Comment by hoangtdTcom** [comment]
Is there any way I can view the content saved in the index.bin file?

**Comment by sankovalev** [comment]
It's faiss index, so you can do `faiss.read_index()`
In fact it's just a pairs of (vector, label).
